# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-armv7l
# https://conda.anaconda.org/rpi/linux-armv7l/ca-certificates-2017.7.27.1-0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/certifi-2018.1.18-py36h85a5227_0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/libgfortran-3.0.0-0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/ncurses-5.9-0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/numpy-1.14.0-py36h73aad69_0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/openblas-0.2.19-0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/openssl-1.0.2l-0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/pandas-0.22.0-py36hce781a7_0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/pip-9.0.1-py36_0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/python-3.6.3-hea4cac4_0.tar.bz2
# https://conda.anaconda.org/rpi/noarch/python-dateutil-2.6.1-py_0.tar.bz2
# https://conda.anaconda.org/poehlmann/linux-armv7l/python-seabreeze-0.6.0-py36_0.tar.bz2
# https://conda.anaconda.org/rpi/noarch/pytz-2017.3-pyh61df4b5_0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/readline-6.3-0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/setuptools-38.4.0-py36hd934b87_0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/six-1.11.0-py36h1999902_0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/sqlite-3.15.0-0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/tk-8.6.6-0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/wheel-0.30.0-py36h76583d5_0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/xz-5.2.2-0.tar.bz2
# https://conda.anaconda.org/rpi/linux-armv7l/zlib-1.2.11-0.tar.bz2

name: chemiosbrain-environment
channels:
  - rpi
  - conda-forge
  - anaconda
dependencies:
  - arrow:
      